import type { Contact } from '@/types/contact';

export const mockContacts: Contact[] = [
  {
    id: '1',
    firstName: 'Emma',
    lastName: 'Chen',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face',
    location: { lat: 37.7749, lng: -122.4194, city: 'San Francisco', country: 'USA' },
    birthYear: 1995,
    tags: ['designer', 'ux', 'startup'],
    languages: ['English', 'Mandarin'],
    bio: 'Product designer passionate about creating intuitive experiences.',
    email: 'emma@example.com',
    socialLinks: [
      { platform: 'linkedin', url: 'https://linkedin.com/in/emmachen' },
      { platform: 'instagram', url: 'https://instagram.com/emmachen' },
    ],
    attributes: { company: 'Figma', role: 'Senior Designer' },
  },
  {
    id: '2',
    firstName: 'Marcus',
    lastName: 'Johnson',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    location: { lat: 51.5074, lng: -0.1278, city: 'London', country: 'UK' },
    birthYear: 1988,
    tags: ['engineer', 'backend', 'fintech'],
    languages: ['English'],
    bio: 'Backend engineer building scalable financial systems.',
    email: 'marcus@example.com',
    socialLinks: [
      { platform: 'linkedin', url: 'https://linkedin.com/in/marcusj' },
      { platform: 'github', url: 'https://github.com/marcusj' },
    ],
    attributes: { company: 'Stripe', role: 'Staff Engineer' },
  },
  {
    id: '3',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    photoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    location: { lat: 35.6762, lng: 139.6503, city: 'Tokyo', country: 'Japan' },
    birthYear: 1992,
    tags: ['product', 'manager', 'tech'],
    languages: ['Japanese', 'English'],
    bio: 'Product manager bridging East and West tech ecosystems.',
    email: 'yuki@example.com',
    socialLinks: [
      { platform: 'linkedin', url: 'https://linkedin.com/in/yukitanaka' },
      { platform: 'twitter', url: 'https://twitter.com/yukitanaka' },
    ],
    attributes: { company: 'Mercari', role: 'Product Lead' },
  },
  {
    id: '4',
    firstName: 'Sofia',
    lastName: 'Rodriguez',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
    location: { lat: -34.6037, lng: -58.3816, city: 'Buenos Aires', country: 'Argentina' },
    birthYear: 1997,
    tags: ['developer', 'frontend', 'react'],
    languages: ['Spanish', 'English', 'Portuguese'],
    bio: 'Frontend developer crafting beautiful web experiences.',
    email: 'sofia@example.com',
    socialLinks: [
      { platform: 'linkedin', url: 'https://linkedin.com/in/sofiarodriguez' },
      { platform: 'github', url: 'https://github.com/sofiarodriguez' },
    ],
    attributes: { company: 'Vercel', role: 'Developer Advocate' },
  },
  {
    id: '5',
    firstName: 'Ahmed',
    lastName: 'Hassan',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    location: { lat: 25.2048, lng: 55.2708, city: 'Dubai', country: 'UAE' },
    birthYear: 1985,
    tags: ['entrepreneur', 'investor', 'tech'],
    languages: ['Arabic', 'English', 'French'],
    bio: 'Tech entrepreneur and angel investor in MENA region.',
    email: 'ahmed@example.com',
    socialLinks: [
      { platform: 'linkedin', url: 'https://linkedin.com/in/ahmedhassan' },
      { platform: 'twitter', url: 'https://twitter.com/ahmedhassan' },
    ],
    attributes: { company: 'Careem', role: 'Founder' },
  },
  {
    id: '6',
    firstName: 'Lena',
    lastName: 'Müller',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    location: { lat: 52.52, lng: 13.405, city: 'Berlin', country: 'Germany' },
    birthYear: 1990,
    tags: ['data', 'scientist', 'ml'],
    languages: ['German', 'English'],
    bio: 'Data scientist working on ML applications in healthcare.',
    email: 'lena@example.com',
    socialLinks: [
      { platform: 'linkedin', url: 'https://linkedin.com/in/lenamuller' },
      { platform: 'github', url: 'https://github.com/lenamuller' },
    ],
    attributes: { company: 'Ada Health', role: 'Lead Data Scientist' },
  },
  {
    id: '7',
    firstName: 'Raj',
    lastName: 'Patel',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    location: { lat: 19.076, lng: 72.8777, city: 'Mumbai', country: 'India' },
    birthYear: 1993,
    tags: ['mobile', 'developer', 'ios'],
    languages: ['Hindi', 'English', 'Gujarati'],
    bio: 'iOS developer building apps used by millions.',
    email: 'raj@example.com',
    socialLinks: [
      { platform: 'linkedin', url: 'https://linkedin.com/in/rajpatel' },
      { platform: 'twitter', url: 'https://twitter.com/rajpatel' },
    ],
    attributes: { company: 'PhonePe', role: 'Senior iOS Developer' },
  },
  {
    id: '8',
    firstName: 'Olivia',
    lastName: 'Smith',
    location: { lat: -33.8688, lng: 151.2093, city: 'Sydney', country: 'Australia' },
    birthYear: 1998,
    tags: ['marketing', 'growth', 'saas'],
    languages: ['English'],
    bio: 'Growth marketer helping SaaS companies scale.',
    email: 'olivia@example.com',
    socialLinks: [
      { platform: 'linkedin', url: 'https://linkedin.com/in/oliviasmith' },
    ],
    attributes: { company: 'Canva', role: 'Growth Lead' },
  },
  {
    id: '9',
    firstName: 'Pierre',
    lastName: 'Dubois',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    location: { lat: 48.8566, lng: 2.3522, city: 'Paris', country: 'France' },
    birthYear: 1987,
    tags: ['architect', 'cloud', 'aws'],
    languages: ['French', 'English'],
    bio: 'Cloud architect designing resilient distributed systems.',
    email: 'pierre@example.com',
    socialLinks: [
      { platform: 'linkedin', url: 'https://linkedin.com/in/pierredubois' },
      { platform: 'github', url: 'https://github.com/pierredubois' },
    ],
    attributes: { company: 'Datadog', role: 'Principal Architect' },
  },
  {
    id: '10',
    firstName: 'Nina',
    lastName: 'Kowalski',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face',
    location: { lat: 52.2297, lng: 21.0122, city: 'Warsaw', country: 'Poland' },
    birthYear: 2000,
    tags: ['designer', 'brand', 'creative'],
    languages: ['Polish', 'English', 'German'],
    bio: 'Brand designer creating visual identities for startups.',
    email: 'nina@example.com',
    socialLinks: [
      { platform: 'instagram', url: 'https://instagram.com/ninakowalski' },
      { platform: 'dribbble', url: 'https://dribbble.com/ninakowalski' },
    ],
    attributes: { company: 'Freelance', role: 'Brand Designer' },
  },
  {
    id: '11',
    firstName: 'Carlos',
    lastName: 'Silva',
    photoUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150&h=150&fit=crop&crop=face',
    location: { lat: -23.5505, lng: -46.6333, city: 'São Paulo', country: 'Brazil' },
    birthYear: 1991,
    tags: ['cto', 'startup', 'fullstack'],
    languages: ['Portuguese', 'English', 'Spanish'],
    bio: 'CTO building the next generation of fintech in LatAm.',
    email: 'carlos@example.com',
    socialLinks: [
      { platform: 'linkedin', url: 'https://linkedin.com/in/carlossilva' },
      { platform: 'twitter', url: 'https://twitter.com/carlossilva' },
    ],
    attributes: { company: 'Nubank', role: 'CTO' },
  },
  {
    id: '12',
    firstName: 'Anna',
    lastName: 'Svensson',
    photoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&h=150&fit=crop&crop=face',
    location: { lat: 59.3293, lng: 18.0686, city: 'Stockholm', country: 'Sweden' },
    birthYear: 1994,
    tags: ['sustainability', 'product', 'cleantech'],
    languages: ['Swedish', 'English', 'Norwegian'],
    bio: 'Product leader in cleantech, fighting climate change.',
    email: 'anna@example.com',
    socialLinks: [
      { platform: 'linkedin', url: 'https://linkedin.com/in/annasvensson' },
    ],
    attributes: { company: 'Northvolt', role: 'Product Director' },
  },
];
